query FetchIssues($name: String!, $owner: String!, $first: Int = 10) {
	repository(name: $name, owner: $owner) {
		id
		issues(first: $first) {
			nodes {
				id
				number
				title
				author {
					login
				}
			}
			pageInfo {
				endCursor
				hasNextPage
				hasPreviousPage
				startCursor
			}
			totalCount
		}
	}
}
