name: Publishing storybook 🎨

on:
  push:
    branches-ignore:
      - docs

permissions:
  contents: write

env:
  TARGET_BRANCH: docs
  TARGET_FOLDER: docs
  APP_PREFIX: /backendless-apollo-client/${GITHUB_REF_NAME}
  STORYBOOK_STATIC_TARGET: docs/${GITHUB_REF_NAME}

jobs:
  publish:
    name: Checkout, build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: APP_PREFIX=${APP_PREFIX} npm run storybook:build
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ${TARGET_BRANCH}
          folder: storybook-static
          target-folder: ${STORYBOOK_STATIC_TARGET}

  readme:
    needs: [publish]
    name: Update index.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: docs
      - run: |
          SANITIZED_REF_NAME=$(printf '%s\n' "${GITHUB_REF_NAME}" | sed -e 's/[\/&]/\\&/g')
          sed -i "/\[${SANITIZED_REF_NAME}\]/d" docs/index.md
          echo "| [$GITHUB_REF_NAME]($GITHUB_REF_NAME) | [\`$GITHUB_SHA\`](https://github.com/${{ github.repository }}/tree/$GITHUB_SHA) |" >> docs/index.md
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ${TARGET_BRANCH}
          folder: ${TARGET_FOLDER}
          target-folder: ${TARGET_FOLDER}
