name: Publishing storybook 🎨

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  REPO_URL: ${{ github.event.repository.html_url }} # https://github.com/boonya/backendless-apollo-client
  REPO_NAME: ${{ github.event.repository.name }} # backendless-apollo-client
  GH_PAGES_URL: ${{ github.event.repository.homepage }} # https://boonya.github.io/backendless-apollo-client/
  GH_PAGES_BRANCH: docs
  GH_PAGES_FOLDER: docs
  MD_FILE: index.md
  SHA: ${{ github.event.after }} # sha hash of head
  REF_NAME: ${{ github.head_ref || github.ref_name }} # branch or tag name

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Print env context
        run: |
          echo "${{ toJSON(env) }}"
      - name: Print github.event context
        run: |
          echo "${{ toJSON(github.event) }}"
      - name: Print github context
        run: |
          echo "${{ toJSON(github) }}"

  publish:
    name: Checkout, build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: "Prepare variables"
        run: |
          echo "APP_PREFIX=/${REPO_NAME}/${REF_NAME}" >> $GITHUB_ENV
          echo "STORYBOOK_STATIC_TARGET=/${GH_PAGES_FOLDER}/${REF_NAME}" >> $GITHUB_ENV
      - run: npm ci
      - name: "Run storybook build"
        run: APP_PREFIX=${APP_PREFIX} npm run storybook:build
      - name: "Publish bundle"
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ${{ env.GH_PAGES_BRANCH }}
          folder: storybook-static
          target-folder: ${{ env.STORYBOOK_STATIC_TARGET }}

  readme:
    needs: publish
    name: "Update a catalog"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GH_PAGES_BRANCH }}
      - name: "Update a catalog file"
        run: |
          SANITIZED_REF_NAME=$(printf '%s\n' "${REF_NAME}" | sed -e 's/[\/&]/\\&/g')
          sed -i "/\[${SANITIZED_REF_NAME}\]/d" ${GH_PAGES_FOLDER}/${MD_FILE}
          echo "| [${REF_NAME}](${GH_PAGES_URL}${REF_NAME}) | [\`${SHA}\`](${REPO_URL}/tree/${SHA}) |" >> ${GH_PAGES_FOLDER}/${MD_FILE}
      - name: "Publish changes"
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ${{ env.GH_PAGES_BRANCH }}
          folder: ${{ env.GH_PAGES_FOLDER }}
          target-folder: ${{ env.GH_PAGES_FOLDER }}

  comment:
    needs: publish
    if: ${{ github.event_name == 'pull_request' }}
    name: "Add a comment to the PR"
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: instance of storybook deployed
      - name: Create of update a comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            ### You can play with these changes at [the separate instance of storybook deployed.][1]
            [1]: ${{ github.event.repository.homepage }}${{ github.head_ref }}
          reactions: rocket
