name: Publishing storybook 🎨

on:
  push:
    branches-ignore:
      - docs

permissions:
  contents: write

env:
  GH_PAGES_BRANCH: docs
  GH_PAGES_FOLDER: docs
  MD_FILE: index.md

jobs:
  publish:
    name: Checkout, build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - name: "Prepare variables"
        run: |
          echo "APP_PREFIX=/backendless-apollo-client/${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "STORYBOOK_STATIC_TARGET=/${GH_PAGES_FOLDER}/${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - run: APP_PREFIX=${APP_PREFIX} npm run storybook:build
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ${{ env.GH_PAGES_BRANCH }}
          folder: storybook-static
          target-folder: ${{ env.STORYBOOK_STATIC_TARGET}}

  readme:
    needs: [publish]
    name: Update index.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GH_PAGES_BRANCH }}
      - run: |
          SANITIZED_REF_NAME=$(printf '%s\n' "${GITHUB_REF_NAME}" | sed -e 's/[\/&]/\\&/g')
          sed -i "/\[${SANITIZED_REF_NAME}\]/d" ${GH_PAGES_FOLDER}/${MD_FILE}
          echo "| [${GITHUB_REF_NAME}](${GITHUB_REF_NAME}) | [\`${GITHUB_SHA}\`](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/${GITHUB_SHA}) |" >> docs/index.md
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ${{ env.GH_PAGES_BRANCH }}
          folder: ${{ env.GH_PAGES_FOLDER }}
          target-folder: ${{ env.GH_PAGES_FOLDER }}
