name: Cleanup storybook 🧹

# Note: This event will only trigger a workflow run if the workflow file is on the default branch.
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#delete
on: [delete]

permissions:
  contents: write

env:
  GH_PAGES_BRANCH: docs
  GH_PAGES_FOLDER: docs
  MD_FILE: index.md

jobs:
  delete:
    name: Delete redundant directory 🗑
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GH_PAGES_BRANCH }}
      - name: "Remove a bundle directory"
        run: rm -rf "${GH_PAGES_FOLDER}/${{ github.event.ref }}"
      - name: "Update a catalog file"
        run: |
          SANITIZED_REF_NAME=$(printf '%s\n' "${{ github.event.ref }}" | sed -e 's/[\/&]/\\&/g')
          sed -i "/\[${SANITIZED_REF_NAME}\]/d" ${GH_PAGES_FOLDER}/${MD_FILE}
      - uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: ${{ env.GH_PAGES_BRANCH }}
          folder: ${{ env.GH_PAGES_FOLDER }}
          target-folder: ${{ env.GH_PAGES_FOLDER }}
